### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by jamesviggiano** [dylankilkenny/CoinMarketCap-Historical-Prices#11]
Hi Dylan, thank you very much for building this. It's been awesome. Recently I've run into some issues - sorry if this is the wrong place to ask for help. 

When I run python3 crypto_history.py I get the following error usually around the 9th or 10th coin in the counter and then it stops. 

~/CoinMarketCap-Historical-Prices$ python3 crypto_history.py 20190101 20190411
Traceback (most recent call last):
  File "crypto_history.py", line 79, in <module>
    _gather(startdate, enddate)
  File "crypto_history.py", line 57, in _gather
    headers, historicaldata = gather(startdate, enddate, names)
  File "crypto_history.py", line 39, in gather
    for row in table.find_all('tr'):
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by CryptoStatistical** [comment]
Recently they added Cloudflare to block scraping.
https://github.com/dylankilkenny/CoinMarketCap-Historical-Prices/compare/master...CryptoStatistical:patch-1

**Comment by jamesviggiano** [comment]
Thank you that fixed it! cheers
